### ISSUE TITLE
Fail to install on Redmine 4.1.1

### ISSUE THREAD

**Issue by mcortellino** [dmp1ce/redmine-contracts-with-time-tracking-plugin#69]
Are there any chanche to get this great plugin works on Redmine 4.1.1?
I've tried the install instructions but I got this error:

`rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/var/www/redmine/plugins/contracts/init.rb:39:in `<top (required)>'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/www/redmine/lib/redmine/plugin.rb:181:in `block in load'
/var/www/redmine/lib/redmine/plugin.rb:172:in `each'
/var/www/redmine/lib/redmine/plugin.rb:172:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/www/redmine/vendor/cache/ruby/2.4.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)`

**Comment by dmp1ce** [comment]
> Are there any chanche to get this great plugin works on Redmine 4.1.1?

Probably not. This project isn't being supported any longer.

**Comment by guitooliveira** [comment]
Yes, i create a fork with modified codes to run in redmine 4.1.1 as well: https://github.com/guitooliveira/redmine-contracts-with-time-tracking-plugin

**Comment by dmp1ce** [comment]
Thank you. Forking is probably for the best at this point.
